spring:
  application:
    name: myApp

server:
  servlet:
    session:
      cookie:
        http-only: true

springdoc:
  show-actuator: true

---
# Conditionally disable springdoc on missing api-docs profile
spring:
  config:
    activate:
      on-profile: '!api-docs'
springdoc:
  api-docs:
    enabled: false
---